version: "3.8"
services:
  l7_validation:
    container_name: l7_validation
    build:
      context: .
      args:
        FLASK_RUN_HOST: "${FLASK_RUN_HOST}"
        FLASK_RUN_PORT: "${FLASK_RUN_PORT}"
        FLASK_ENV: "${FLASK_ENV}"
        CONFIG_FILE: "${ENV_FILE_PATH}"
    volumes:
      - ./:/app
    networks:
      - l7_db_nw
    depends_on:
      # build those images first
      - local_pgdb
    ports:
      - "${FLASK_ENV_PORT}"
    command: python run.py
  local_pgdb:
    image: postgres:11
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - l7_db_nw
  pgadmin:
    depends_on:
      - local_pgdb
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
      #PGADMIN_LISTEN_PORT: "5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - l7_db_nw
volumes:
  local_pgdata:
  pgadmin_data:
networks:
  l7_db_nw:
    driver: bridge